[tool.poetry]
name = "lightningrobot-cli"
version = "0.0.1"
description = "LightningRobot's cli."
authors = ["MeowSauce <meowsauce@hotmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
